### ISSUE TITLE
Mineral classification (Strunz)

### ISSUE THREAD

**Issue by EstherMoreno** [PIWEEK/mineralis#2]
The user should be able to group the minerals by:

I. Elements
II. Sulfides and sulfosalts
III. Halides
IV. Oxides, hydroxides and arsenites
V. Carbonates and nitrates
VI. Borates
VII. Sulfates, chromates, molybdates and tungstates
VIII. Phosphates, arsenates and vanadates
IX. Silicates
X. Organic compounds

:)

**Comment by yamila-moreno** [comment]
"Group" means filter?

For each mineral the user fills those fields?

**Comment by yamila-moreno** [comment]
These items are a list, and the user can choose one of them.

**Comment by yamila-moreno** [comment]
Done!
